# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "example/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
    technical-debt:
      threshold: 1
      todo-cost: 50
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322

  metrics-exclude:
    - test/**
    # - lib/src/some_file.dart
  rules:
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-const-border-radius
    - avoid-unused-parameters
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
    - double-literal-format
    # - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    # new
    # - avoid-throw-in-catch-block
    # - no-boolean-literal-compare
    - avoid-unnecessary-type-casts
    - binary-expression-operand-order
    # - avoid-non-null-assertion
    - avoid-dynamic
    - no-empty-block
    - avoid-missing-enum-constant-in-map
    - double-literal-format
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-match-file-name
    - prefer-conditional-expressions
    - prefer-first
    - prefer-last
    # - prefer-correct-identifier-length:
    #     exceptions: [ 'z' ]
    #     max-identifier-length: 30
    #     min-identifier-length: 4
    - prefer-single-widget-per-file:
      # ignore-private-widgets: true
    - member-ordering:
        alphabetize-by-type: true
        order:
          - public-fields
          - private-fields
          - constructors
  anti-patterns:
    - long-method
    - long-parameter-list